### model
model_name_or_path: Qwen/Qwen2-7B-Instruct
adapter_name_or_path: saves/qwen2-7b/lora/sft

### method
finetuning_type: lora

### dataset
task: mmlu_test  # choices: [mmlu_test, ceval_validation, cmmlu_test]
template: fewshot
lang: zh
n_shot: 5

### output
save_dir: saves/qwen2-7b/lora/eval

### eval
batch_size: 4
